Repository ynput/ayon-syncsketch, pull requests merged in 2024-10, with the labels that each got.

#7 Refactor OpenPype to AYON
  client/ayon_syncsketch/addon.py
  client/ayon_syncsketch/plugins/publish/collect_project_id.py
  client/ayon_syncsketch/plugins/publish/collect_server_active_config.py
  client/ayon_syncsketch/plugins/publish/integrate_reviewables.py
  client/ayon_syncsketch/plugins/publish/validate_server_connection.py
  server/settings/main.py
  server/settings/publish_plugins.py
  tests/client/ayon_syncsketch/test_addon.py
  tests/config_tests.py
  tests/lib.py
Labels: type: enhancement, type: maintenance

#8 Chore: Update to new repository structure
  .github/workflows/pr_linting.yml
  .github/workflows/release_trigger.yml
  .gitignore
  client/ayon_syncsketch/__init__.py
  client/ayon_syncsketch/addon.py
  client/ayon_syncsketch/plugins/publish/integrate_reviewables.py
  client/ayon_syncsketch/plugins/publish/validate_server_connection.py
  client/ayon_syncsketch/version.py
  client/pyproject.toml
  create_package.py
  package.py
  ruff.toml
  server/__init__.py
  service/docker-compose.yml
  service/processor/__init__.py
  service/processor/event_handlers/review_session_end.py
  service/processor/lib/__init__.py
  service/processor/lib/event_abstraction.py
  service/processor/processor.py
  syncsketch_common/config.py
  syncsketch_common/constants.py
  syncsketch_common/server_handler.py
  tests/client/ayon_syncsketch/api/test_server_handler.py
  tests/lib.py
  version.py
Labels: type: enhancement, bump minor

#9 Do not crash Syncsketch addon if it cannot connect to the Syncsketch server due to wrong server or credentials
  server/__init__.py
Labels: type: bug, sponsored
